# Generated by Django 4.2.7 on 2023-12-20 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flareuprecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='uricacidrecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
