# Generated by Django 4.2.7 on 2023-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('session_key', models.CharField(max_length=255)),
            ],
        ),
    ]
